# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 778f57c1bfa1093b518032409c218cc2ec12ef535bbf9db0d43dc3bfa654ac696253741c9fb8ef09c7f5a6a948070299591f02a7cc62445529418d7cff288385

test:
  secret_key_base: 446c4970467210461d987b88d16f7c61527ba302a55655a6fdf2a8889018b5d6ab3bb730fb5bb6285ffbc68661095c1110bb633ff3932ef8208fc006bc380154

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
