require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PersonalObjectivesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PersonalObjective. As you add validations to PersonalObjective, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PersonalObjectivesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all personal_objectives as @personal_objectives" do
      personal_objective = PersonalObjective.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:personal_objectives)).to eq([personal_objective])
    end
  end

  describe "GET #show" do
    it "assigns the requested personal_objective as @personal_objective" do
      personal_objective = PersonalObjective.create! valid_attributes
      get :show, params: {id: personal_objective.to_param}, session: valid_session
      expect(assigns(:personal_objective)).to eq(personal_objective)
    end
  end

  describe "GET #new" do
    it "assigns a new personal_objective as @personal_objective" do
      get :new, params: {}, session: valid_session
      expect(assigns(:personal_objective)).to be_a_new(PersonalObjective)
    end
  end

  describe "GET #edit" do
    it "assigns the requested personal_objective as @personal_objective" do
      personal_objective = PersonalObjective.create! valid_attributes
      get :edit, params: {id: personal_objective.to_param}, session: valid_session
      expect(assigns(:personal_objective)).to eq(personal_objective)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PersonalObjective" do
        expect {
          post :create, params: {personal_objective: valid_attributes}, session: valid_session
        }.to change(PersonalObjective, :count).by(1)
      end

      it "assigns a newly created personal_objective as @personal_objective" do
        post :create, params: {personal_objective: valid_attributes}, session: valid_session
        expect(assigns(:personal_objective)).to be_a(PersonalObjective)
        expect(assigns(:personal_objective)).to be_persisted
      end

      it "redirects to the created personal_objective" do
        post :create, params: {personal_objective: valid_attributes}, session: valid_session
        expect(response).to redirect_to(PersonalObjective.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved personal_objective as @personal_objective" do
        post :create, params: {personal_objective: invalid_attributes}, session: valid_session
        expect(assigns(:personal_objective)).to be_a_new(PersonalObjective)
      end

      it "re-renders the 'new' template" do
        post :create, params: {personal_objective: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested personal_objective" do
        personal_objective = PersonalObjective.create! valid_attributes
        put :update, params: {id: personal_objective.to_param, personal_objective: new_attributes}, session: valid_session
        personal_objective.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested personal_objective as @personal_objective" do
        personal_objective = PersonalObjective.create! valid_attributes
        put :update, params: {id: personal_objective.to_param, personal_objective: valid_attributes}, session: valid_session
        expect(assigns(:personal_objective)).to eq(personal_objective)
      end

      it "redirects to the personal_objective" do
        personal_objective = PersonalObjective.create! valid_attributes
        put :update, params: {id: personal_objective.to_param, personal_objective: valid_attributes}, session: valid_session
        expect(response).to redirect_to(personal_objective)
      end
    end

    context "with invalid params" do
      it "assigns the personal_objective as @personal_objective" do
        personal_objective = PersonalObjective.create! valid_attributes
        put :update, params: {id: personal_objective.to_param, personal_objective: invalid_attributes}, session: valid_session
        expect(assigns(:personal_objective)).to eq(personal_objective)
      end

      it "re-renders the 'edit' template" do
        personal_objective = PersonalObjective.create! valid_attributes
        put :update, params: {id: personal_objective.to_param, personal_objective: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested personal_objective" do
      personal_objective = PersonalObjective.create! valid_attributes
      expect {
        delete :destroy, params: {id: personal_objective.to_param}, session: valid_session
      }.to change(PersonalObjective, :count).by(-1)
    end

    it "redirects to the personal_objectives list" do
      personal_objective = PersonalObjective.create! valid_attributes
      delete :destroy, params: {id: personal_objective.to_param}, session: valid_session
      expect(response).to redirect_to(personal_objectives_url)
    end
  end

end
